version: "3.8"
services:
  auth:
    build: ./ProductsSystem.Auth
    ports: 
      - "8000:5001" #remove
    container_name: authservice
    networks: 
      - api
    depends_on:
      - authdb
  authdb:
    networks: 
      - api
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "SqlPassword123~"
      ACCEPT_EULA: "Y"
  gateway:
    build: ./ProductSystem.Gateway
    container_name: gateway
    networks: 
      - api
    ports:
      - "8001:5002"
  manag:
    build: ./ProductSystem.Management
    ports: 
      - "8002:5003" #remove
    container_name: managservice
    networks: 
      - api
    depends_on:
      - managdb
  managdb:
    networks: 
      - api
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "SqlPassword123~"
      ACCEPT_EULA: "Y"
networks:    
  api:
    driver: bridge