version: "3.8"
services:
  auth:
    build: ./ProductsSystem.Auth
    container_name: authservice
    networks: 
      - api
    depends_on:
      - authdb
  authdb:
    networks: 
      - api
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "SqlPassword123~"
      ACCEPT_EULA: "Y"
  gateway:
    build: ./ProductSystem.Gateway
    container_name: gateway
    networks: 
      - api
    ports:
      - "8001:5002"
  manag:
    build: ./ProductSystem.Management
    ports: 
      - "8002:5003" #remove
    container_name: managservice
    networks: 
      - api
    depends_on:
      - managdb
      - rabbitmq
  managdb:
    networks: 
      - api
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "SqlPassword123~"
      ACCEPT_EULA: "Y"
  rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    networks: 
      - api
    labels:
      NAME: "rabbitmq"
    ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672"
networks:    
  api:
    driver: bridge