version: "3.8"
services:
  auth:
    build: ./ProductsSystem.Auth
    ports:
      - "8000:5001"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "SqlPassword123~"
      ACCEPT_EULA: "Y"
  gateway:
    build: ./ProductSystem.Gateway
    ports:
      - "8001:5002"